# Implicit variable dependencies:
#   BuildPlatform
#   BuildConfiguration

parameters:
  - name: project
  - name: projects
  - name: debug
    default: false

steps:
  - task: PowerShell@2
    displayName: Show Variables
    inputs:
      targetType: inline
      script: |
          Write-Host "[${env:BuildPlatform}]"
          Write-Host "[${env:BuildConfiguration}]"
    condition: ${{ parameters.debug }}
