parameters:
  - name: framework
  - name: version

steps:
  - task: Bash@3
    displayName: Setting ${{ parameters.framework }} to version ${{ parameters.version }}
    inputs:
      targetType: inline
      script: |
        ls -l /Library/Frameworks/${{ parameters.framework }}.framework/Versions/Current
        sudo rm -f /Library/Frameworks/${{ parameters.framework }}.framework/Versions/Current
        sudo ln -s /Library/Frameworks/${{ parameters.framework }}.framework/Versions/${{ parameters.version }} /Library/Frameworks/${{ parameters.framework }}.framework/Versions/Current
        ls -l /Library/Frameworks/${{ parameters.framework }}.framework/Versions/Current
