#!/usr/bin/env bash

echo "APPCENTER_BUILD_ID [$APPCENTER_BUILD_ID]"
echo "APPCENTER_BRANCH [$APPCENTER_BRANCH]"
echo "APPCENTER_SOURCE_DIRECTORY [$APPCENTER_SOURCE_DIRECTORY]"
echo "APPCENTER_OUTPUT_DIRECTORY [$APPCENTER_OUTPUT_DIRECTORY]"
echo "APPCENTER_TRIGGER [$APPCENTER_TRIGGER]"
echo "pwsh [$(which pwsh)]"

if [ -n "$UPDATE_VERSION" ]; then
  echo "UNJAMMIT_BASE_VERSION [$UNJAMMIT_BASE_VERSION]"
  echo "BUNDLE_NAME [$BUNDLE_NAME]"
  echo "DISPLAY_NAME [$DISPLAY_NAME]"
fi
