//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jammit.Forms.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localized {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localized() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Jammit.Forms.Resources.Localized", typeof(Localized).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CatalogPage_DownloadButton {
            get {
                return ResourceManager.GetString("CatalogPage_DownloadButton", resourceCulture);
            }
        }
        
        internal static string CatalogPage_DownloadButtonClicked_AlertTitle {
            get {
                return ResourceManager.GetString("CatalogPage_DownloadButtonClicked_AlertTitle", resourceCulture);
            }
        }
        
        internal static string CatalogPage_DownloadButtonClicked_CatchMessage {
            get {
                return ResourceManager.GetString("CatalogPage_DownloadButtonClicked_CatchMessage", resourceCulture);
            }
        }
        
        internal static string CatalogPage_DownloadButtonClicked_CatchTitle {
            get {
                return ResourceManager.GetString("CatalogPage_DownloadButtonClicked_CatchTitle", resourceCulture);
            }
        }
        
        internal static string CatalogPage_LoadButton {
            get {
                return ResourceManager.GetString("CatalogPage_LoadButton", resourceCulture);
            }
        }
        
        internal static string CatalogPage_LoadCatalogCatchCancel {
            get {
                return ResourceManager.GetString("CatalogPage_LoadCatalogCatchCancel", resourceCulture);
            }
        }
        
        internal static string CatalogPage_LoadCatalogCatchTitle {
            get {
                return ResourceManager.GetString("CatalogPage_LoadCatalogCatchTitle", resourceCulture);
            }
        }
        
        internal static string Client_AuthStatusLabel {
            get {
                return ResourceManager.GetString("Client_AuthStatusLabel", resourceCulture);
            }
        }
        
        internal static string Client_RequestAuthLabel {
            get {
                return ResourceManager.GetString("Client_RequestAuthLabel", resourceCulture);
            }
        }
        
        internal static string LibraryPage_DeleteOption {
            get {
                return ResourceManager.GetString("LibraryPage_DeleteOption", resourceCulture);
            }
        }
        
        internal static string MenuPage_AboutButton {
            get {
                return ResourceManager.GetString("MenuPage_AboutButton", resourceCulture);
            }
        }
        
        internal static string MenuPage_CatalogItem {
            get {
                return ResourceManager.GetString("MenuPage_CatalogItem", resourceCulture);
            }
        }
        
        internal static string MenuPage_Import {
            get {
                return ResourceManager.GetString("MenuPage_Import", resourceCulture);
            }
        }
        
        internal static string MenuPage_ImportCatch {
            get {
                return ResourceManager.GetString("MenuPage_ImportCatch", resourceCulture);
            }
        }
        
        internal static string MenuPage_ImportCatchTitle {
            get {
                return ResourceManager.GetString("MenuPage_ImportCatchTitle", resourceCulture);
            }
        }
        
        internal static string MenuPage_LibraryItem {
            get {
                return ResourceManager.GetString("MenuPage_LibraryItem", resourceCulture);
            }
        }
        
        internal static string MenuPage_OpenButton {
            get {
                return ResourceManager.GetString("MenuPage_OpenButton", resourceCulture);
            }
        }
        
        internal static string MenuPage_SettingsItem {
            get {
                return ResourceManager.GetString("MenuPage_SettingsItem", resourceCulture);
            }
        }
        
        internal static string MenuPage_Title {
            get {
                return ResourceManager.GetString("MenuPage_Title", resourceCulture);
            }
        }
        
        internal static string SettingsPage_DeleteDataButton {
            get {
                return ResourceManager.GetString("SettingsPage_DeleteDataButton", resourceCulture);
            }
        }
        
        internal static string SettingsPage_DeleteDataConfirm {
            get {
                return ResourceManager.GetString("SettingsPage_DeleteDataConfirm", resourceCulture);
            }
        }
        
        internal static string SettingsPage_DeleteDataNo {
            get {
                return ResourceManager.GetString("SettingsPage_DeleteDataNo", resourceCulture);
            }
        }
        
        internal static string SettingsPage_DeleteDataText {
            get {
                return ResourceManager.GetString("SettingsPage_DeleteDataText", resourceCulture);
            }
        }
        
        internal static string SettingsPage_DeleteDataYes {
            get {
                return ResourceManager.GetString("SettingsPage_DeleteDataYes", resourceCulture);
            }
        }
        
        internal static string SettingsPage_LanguageLabel {
            get {
                return ResourceManager.GetString("SettingsPage_LanguageLabel", resourceCulture);
            }
        }
        
        internal static byte[] SettingsPage_LocaleImage {
            get {
                object obj = ResourceManager.GetObject("SettingsPage_LocaleImage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static string SettingsPage_SaveButton {
            get {
                return ResourceManager.GetString("SettingsPage_SaveButton", resourceCulture);
            }
        }
        
        internal static string SettingsPage_ServiceUriEntryPlaceholder {
            get {
                return ResourceManager.GetString("SettingsPage_ServiceUriEntryPlaceholder", resourceCulture);
            }
        }
        
        internal static string SettingsPage_ServiceUriLabel {
            get {
                return ResourceManager.GetString("SettingsPage_ServiceUriLabel", resourceCulture);
            }
        }
        
        internal static string SongInfo_Album {
            get {
                return ResourceManager.GetString("SongInfo_Album", resourceCulture);
            }
        }
        
        internal static string SongInfo_Artist {
            get {
                return ResourceManager.GetString("SongInfo_Artist", resourceCulture);
            }
        }
        
        internal static string SongInfo_Instrument {
            get {
                return ResourceManager.GetString("SongInfo_Instrument", resourceCulture);
            }
        }
        
        internal static string SongInfo_Title {
            get {
                return ResourceManager.GetString("SongInfo_Title", resourceCulture);
            }
        }
        
        internal static string SongPage_CloseButton {
            get {
                return ResourceManager.GetString("SongPage_CloseButton", resourceCulture);
            }
        }
        
        internal static string SongPage_ScoreHiddenLabel {
            get {
                return ResourceManager.GetString("SongPage_ScoreHiddenLabel", resourceCulture);
            }
        }
        
        internal static string SongSearch_Placeholder {
            get {
                return ResourceManager.GetString("SongSearch_Placeholder", resourceCulture);
            }
        }
    }
}
